spring:
  application:
    name: spring-ai-alibaba-qwq-chat-client-example
  ai:
    dashscope:
      api-key: sk-3fa0170f38764f79afe8b365c6ae4cfe
      chat:
        options:
          model: qwen-plus
